#Default port is 8761
server:
  port: 9411

spring:
  application:
    name: zipkin

#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG