
server:
  port: 9000

spring:
  main:
    banner-mode: off
  cloud:
    stream:
      bindings:
        input:
          destination: organization.change
          group: grupo
        inboundOrgChanges:
          destination: orgChangeTopic
          content-type: application/json
          group: licensingGroup

  rabbitmq:
    host: localhost
    username: admin
    password: 123456
    port: 5672

  redis:
    server: localhost
    port: 6379
  cache:
    type: redis

#spring:
#  cloud:
#    stream:
#      bindings:
#        input:
#          destination: orgChangeTopic
#          content-type: application/json
#          group: licensingGroup
#      kafka:
#        binder:
#          zkNodes: localhost:9092
#          brokers: localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8901/user