server:
  port: 5555

  #Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
# to change actuators base path:
      base-path: /tosco
# to show details:
  endpoint:
    health:
      show-details: always

zuul:
  # this is a blacklist of header that zuul wont propagate - we need the authorization, so, his absence means that zuul will propagate it
  sensitiveHeaders: "Cookie,Set-Cookie"
# Mapping routes manually using service discovery
#  ignored-services: '*'
#  prefix: /api
#  routes:
#    organizationservice: /organization/**
#    licensingservice: /licensing/**
# if you want to map static urls to non-JVM services(check sidecar), use this:
#    licensestatic:
#      path: /licensestatic/**
#      url: http://licenseservice-static:8081
#      url: http://licenseservice-static:8081

