version: '2'
services:
  database:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p0stgr@s
      POSTGRES_DB:       eagle_eye_local
    volumes:
      - ../.data/postgres:/var/lib/postgresql/data
  eurekaserver:
    image: com.github.hfantin/eurekasrv:latest
    ports:
      - "8761:8761"
    depends_on:
      - database
  configserver:
    image: com.github.hfantin/confsrv
    ports:
      - "8888:8888"
    environment:
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      ENCRYPT_KEY:       "IMSYMMETRIC"
    depends_on:
      - eurekaserver

  licensingservice:
    image: com.github.hfantin/licensing-service:latest
    ports:
      - "9000:9000"
    environment:
      PROFILE: "default"
      SERVER_PORT: "9000"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT:   "8888"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY:       "IMSYMMETRIC"
    depends_on:
      - configserver
  organizationservice:
    image: com.github.hfantin/organization-service:latest
    ports:
      - "9001:9001"
    environment:
      PROFILE: "default"
      SERVER_PORT: "9001"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT:   "8888"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY:       "IMSYMMETRIC"
    depends_on:
      - configserver
#  organizationservicenew:
#    image: com.github.hfantin/organization-new:latest
#    ports:
#      - "9002:9002"
#    environment:
#      PROFILE: "default"
#      SERVER_PORT: "9002"
#      CONFIGSERVER_URI: "http://configserver:8888"
#      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
#      EUREKASERVER_PORT:   "8761"
#      CONFIGSERVER_PORT:   "8888"
#      DATABASESERVER_PORT: "5432"
#      ENCRYPT_KEY:       "IMSYMMETRIC"
#    depends_on:
#      - configserver
  specialrouteservice:
    image: com.github.hfantin/specialroute-service:latest
    ports:
      - "8910:8910"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8910"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT:   "8888"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY:       "IMSYMMETRIC"
    depends_on:
      - configserver
  zuulserver:
    image: com.github.hfantin/zuulsrv
    ports:
      - "5555:5555"
    environment:
      PROFILE: "default"
      SERVER_PORT: "5555"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:        "8761"
      DATABASESERVER_PORT:      "5432"
      CONFIGSERVER_PORT:        "8888"
      ORGSERVERNEW_PORT:        "8087"
      ENCRYPT_KEY:       "IMSYMMETRIC"
    depends_on:
      - configserver
