server:
  port: 8888
# spring.cloud.config.server.git.uri=${HOME}/workspace/github/springboot-config-file
#spring.cloud.config.server.git.uri=https://github.com/hfantin/microservices-in-action-config-files
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hfantin/microservices-in-action
          # search-paths: config/licensingservice,config/organizationservice
          #search-paths: '*,{application},config/{application}, config/, config/*'
          search-paths: config/*
        encrypt:
          enabled: true


