spring:
  zipkin:
    baseUrl: http://zipkinsrv:9411
#  sleuth:
#    sampler:
#      percentage: 1 # values between 0 and 1 - eg.: .5 means 50%
zuul:
  ignored-services: '*'
  prefix: /api
  routes:
    organizationservice: /organization/**
    licensingservice: /licensing/**

# this is to set the default timeout of hystrix to 2.5 seconds
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2500

signing:
  key: "345345fsdfsf5345"