zuul:
  ignored-services: '*'
  prefix: /api
  routes:
    organizationservice: /organization/**
    licensingservice: /licensing/**

# this is to set the default timeout of hystrix to 2.5 seconds
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2500
# specific for licensing service
    licensingservice:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 7000
# change ribbon default timeout(for configurations that take more than 5 seconds, you need to set both)
licensingservice:
  ribbon:
    ReadTimeout: 7000

signing:
  key: "345345fsdfsf5345"