server:
  port: 9003

spring:
  cloud:
    stream:
      bindings:
        output:
          destination:  orgChangeTopic
          content-type: application/json
      kafka:
        binder:
          autoCreateTopics: true
          zkNodes: localhost:9092
          brokers: localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8901/user