server:
  port: 9001

spring:
  cloud:
    stream:
      bindings:
        organization-channel:
          destination:  orgChangeTopic
          content-type: application/json
#          destination:  organization.change
#          group: grupo
#          durableSubscription: true


#          content-type: application/json
#      kafka:
#        binder:
#          autoCreateTopics: true
#          zkNodes: localhost:9092
#          brokers: localhost:9092
  rabbitmq:
    host: localhost
    username: admin
    password: 123456
    port: 5672

management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8901/user