version: '2'
services:
  configserver:
    image: com.github.hfantin/confsrv
    ports:
      - "8888:8888"
    environment:
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      ENCRYPT_KEY:       "IMSYMMETRIC"